@GymTrack_HostAddress = https://localhost:7266
@token = REPLACE_WITH_JWT

POST {{GymTrack_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@gymtrack.local",
  "password": "Admin123!"
}

###

GET {{GymTrack_HostAddress}}/api/auth/me
Authorization: Bearer {{token}}

###
